"""empty message

Revision ID: 320483dc0c38
Revises: 158579a99401
Create Date: 2022-03-01 12:37:09.180261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '320483dc0c38'
down_revision = '158579a99401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'password')
    # ### end Alembic commands ###
